language: objective-c
osx_image: xcode9
matrix:
  include:
    - env: PLATFORM="iOS"
env:
  global:
    - LANG=en_US.UTF-8
cache:
  - bundler
before_install:
  - brew update
  - brew install swiftlint
  - brew upgrade carthage || true
  - carthage version
  - carthage bootstrap --platform $PLATFORM
  - rake env[http://localhost]
script:
  - rake test $PLATFORM
after_success:
  - bundle exec danger
  - bash <(curl -s https://codecov.io/bash)
  