language: objective-c
osx_image: xcode9
cache:
  - bundler
before_script:
  - bundle exec pod keys set HockeyAPIPath $HockeyAPIPath HockeyPlayoffs
script:
  - bundle exec fastlane test
after_success:
  - bundle exec slather 
