language: objective-c
osx_image: xcode9
matrix:
  include:
    - env: PLATFORM="ios"
env:
  global:
    - LANG=en_US.UTF-8
cache:
  bundler: true
  directories:
    - Carthage
before_install:
  - brew update
  - brew install swiftlint
  - brew upgrade carthage || true
  - carthage version
  - carthage bootstrap --verbose --platform $PLATFORM --cache-builds
  - rake env[http://localhost]
script:
  - rake test:$PLATFORM
after_success:
  - bundle exec danger
  - bash <(curl -s https://codecov.io/bash)
  