language: objective-c
osx_image: xcode8

install:
  - brew update node
  - brew install yarn
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - yarn install

before_script: 
  - yarn build
script:
  - yarn test