language: objective-c
osx_image: xcode6.4
cache: bundler
rvm:
  - system
before_install:
  - sudo gem install bundler
  - xcrun instruments -w "iPhone 6 (8.4 Simulator)" || echo "(Pre)Launched the simulator."
install:
  - bundle install
before_script:
  - bundle exec pod keys set HockeyAPIPath $HockeyAPIPath HockeyPlayoffs
script:
  - bundle exec fastlane test
after_success:
  - bundle exec slather  
